package org.desperu.independentnews.utils

// --- KEY TO PARSE HTML PAGE ---

// Html tag
const val a ="a"
const val A = "A"
const val ARTICLE = "article"
const val BODY = "body"
const val DIV = "div"
const val H1 = "h1"
const val H3 = "h3"
const val HR = "hr"
const val HEADER = "header"
const val IMG = "img"
const val LINK = "link"
const val P = "p"
const val SPAN = "span"
const val TIME = "time"
const val UL = "ul"

// Tag attribute
const val CLASS = "class"
const val DATA_ORIGINAL = "data-original"
const val DATETIME = "datetime"
const val HEIGHT = "height"
const val HREF = "href"
const val ITEMPROP = "itemprop"
const val PUBDATE = "pubdate"
const val REL = "rel"
const val SIZE = "size"
const val SRC = "src"
const val STYLE = "style"
const val WIDTH = "width"

// Attribute value
const val ONE = "1"
const val ARIANNE = "arianne"
const val AUTHOR = "author"
const val ARTICLE_ENTRY = "entry article hentry"
const val CARTOUCHE = "cartouche"
const val CHAPO = "chapo"
const val DATEPUBLICATION = "datepublication"
const val DESCRIPTION = "description"
const val DIVIDER = "divider"
const val ENTRY_TITLE ="h3 entry-title"
const val HEADLINE = "headline"
const val IMAGE = "image"
const val LIENAUTEUR = "lienauteur"
const val LIEN_PAGINATION = "lien_pagination"
const val LIENTHEME = "lientheme"
const val MAIN = "main"
const val MAIN_CONTAINER = "container main-container"
const val REPO_IMAGE_CLASS = "spip_logo spip_logos"
const val STYLESHEET = "stylesheet"
const val TEXTE = "texte"
const val TEXT_ALIGN = "text-align:justify"