package org.desperu.independentnews.utils

// --- KEY TO PARSE HTML PAGE ---

// Html tag
const val a ="a"
const val A = "A"
const val ARTICLE = "article"
const val BODY = "body"
const val DIV = "div"
const val EMBED = "embed"
const val H1 = "h1"
const val H3 = "h3"
const val HR = "hr"
const val HEADER = "header"
const val IMG = "img"
const val LINK = "link"
const val P = "p"
const val PICTURE = "picture"
const val SMALL = "small"
const val SOURCE_TAG = "source"
const val SPAN = "span"
const val TIME = "time"
const val UL = "ul"

// Tag attribute
const val AUDIO = "audio"
const val CLASS = "class"
const val DATA_ORIGINAL = "data-original"
const val DATETIME = "datetime"
const val HEIGHT = "height"
const val HREF = "href"
const val ID = "id"
const val ITEMPROP = "itemprop"
const val ONCLICK = "onclick"
const val PUBDATE = "pubdate"
const val REL = "rel"
const val SIZE = "size"
const val SRC = "src"
const val SRCSET = "srcset"
const val STYLE = "style"
const val WIDTH = "width"

// Attribute value
const val ADDRESS = "adresse"
const val APPEL_DON = "appeldon"
const val ARIANNE = "arianne"
const val AUTHOR = "author"
const val ARTICLE_ENTRY = "entry article hentry"
const val BLOC_ARTICLE = "bloc_article"
const val CARTOUCHE = "cartouche"
const val CHAPO = "chapo"
const val DATE_PUBLICATION = "datepublication"
const val DESCRIPTION = "description"
const val DIVIDER = "divider"
const val ENGLISH ="english"
const val ENTRY_TITLE ="h3 entry-title"
const val HEADLINE = "headline"
const val IMAGE = "image"
const val LIEN_ARTICLE = "lien_article2col mod"
const val LIEN_RUBRIQUE = "lien_rubrique mod"
const val LIEN_AUTEUR = "lienauteur"
const val LIEN_THEME = "lientheme"
const val LIRE = "lire"
const val MAIN = "main"
const val MAIN_CONTAINER = "container main-container"
const val NO_PRINT = "noprint"
const val NOTES = "notes"
const val ONE = "1"
const val PETIT_VERT = "petit_vert"
const val REPO_IMAGE_CLASS = "spip_logo spip_logos"
const val SPAN_CGU = "span7 cgu"
const val SPAN_ECONOMY = "span7 economie"
const val SPAN_MOST_VIEWED = "span7 plus-consultes"
const val SPAN_SUPPORTS = "span7 qui-soutient"
const val STYLE_SHEET = "stylesheet"
const val TEXTE = "texte"
const val TEXT_ALIGN = "text-align:justify"
const val TITRE_ARTICLE = "titre-article"
const val TITRE_PAGE_LIST = "titre-page-liste"
const val TOUS = "tous"